# Generated by Django 5.0 on 2024-01-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='f_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='l_name',
            field=models.CharField(default='g', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='m_name',
            field=models.CharField(default='LL', max_length=255),
            preserve_default=False,
        ),
    ]
